### PR TITLE
Allow saving and loading models (ugly hack).

### PR DESCRIPTION
**Pull request by janstrohbeck**
Tricks keras upon serialization into saving only the name of the metric to be stored, which allows loading the model sucessfully.
See #13

### CODE REVIEW

**Comment by ybubnov** [comment]
@janstrohbeck, well, wow, I need to think about it :smiley:

**Comment by janstrohbeck** [comment]
You don't have to merge that, I just wanted to push it so others can find it as well. It's really annoying when models can't be loaded for evaluation of a trained model. But this PR is just a workaround, no real solution.

**Comment by ybubnov** [comment]
@janstrohbeck, this fix can't get away from my head. Let's stick with this metaprogramming trick, and create an issue for future refactoring.

**Comment by Gunkkk** [comment]
Sorry, I still have the problem with 1.1.0.

**Comment by ybubnov** [comment]
Hi @Gunkkk, can you, please, provide an example of the code that does not work to reproduce the problem?

**Pull request merged**
